name: Lighthouse CI

on:
  push:
    branches:
      - main

jobs:
  lighthouse:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Install Node.js
        uses: actions/setup-node@v2
        with:
          node-version: '14' # Use the appropriate Node.js version

      - name: Install Lighthouse
        run: npm install -g lighthouse

      - name: Install Xvfb
        run: sudo apt-get install -y xvfb

      - name: Start Xvfb
        run: Xvfb :99 -screen 0 1280x1024x24 > /dev/null 2>&1 &

      - name: Run Lighthouse for Desktop
        run: |
          DISPLAY=:99 lighthouse https://cl1.imeapp.in \
            --output html \
            --output-path ./lighthouse-report-desktop.html \
            --emulated-form-factor=desktop \
            --only-categories=performance,accessibility,best-practices,seo
