name: Lighthouse CI

on:
  push:
    branches:
      - main

jobs:
  lighthouse:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Install Node.js
        uses: actions/setup-node@v2
        with:
          node-version: '14'

      - name: Install Lighthouse
        run: npm install -g lighthouse

      - name: Run Lighthouse for Desktop
        run: |
          lighthouse https://cl1.imeapp.in \
            --output html \
            --output-path ./lighthouse-report-desktop.html \
            --emulated-form-factor=desktop \
            --only-categories=performance,accessibility,best-practices,seo

      - name: Upload Lighthouse report for Desktop
        uses: actions/upload-artifact@v2
        with:
          name: lighthouse-report-desktop
          path: ./lighthouse-report-desktop.html

      - name: Run Lighthouse for Mobile
        run: |
          lighthouse https://cl1.imeapp.in \
            --output html \
            --output-path ./lighthouse-report-mobile.html \
            --emulated-form-factor=mobile \
            --only-categories=performance,accessibility,best-practices,seo

      - name: Upload Lighthouse report for Mobile
        uses: actions/upload-artifact@v2
        with:
          name: lighthouse-report-mobile
          path: ./lighthouse-report-mobile.html
